# (C) Akio Jinsenji

name: Auto Merge

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Build-and-AutoMerge:
    runs-on: windows-latest

    steps:
      - name: 🔄 Checkout to the branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: ✅ aAuto merge
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_AUTO_MERGE_TOKEN }}
