# (C) Akio Jinsenji

name: Auto Review

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Review:
    runs-on: windows-latest
    if : ${{ github.actor != 'dependabot[bot]' }}
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 🔄 Checkout to the branch
        uses: actions/checkout@v4

      - name: 🤖 Auto Review
        uses: akiojin/auto-review-github-action@v2
        continue-on-error: true
        with:
          target: 'cs,json,sh,sln,sh,md,yml'
          language: 日本語
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
